export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/'
export const SHOPPING_CART = '/basket'
export const DEVICE_PAGE = '/device'
export const HOME_PAGE = '/'